debian/control{,.in}: Add tzdata to Depends an B/uild-Depends
The tests use ICU and require that this is installed. If it's not, they
fail with messages like

  non262/Date/time-zones.js:41:5 Error: Assertion failed: got "Fri Jul 19 2002 16:10:55 GMT+0000", expected "Fri Jul 19 2002 16:10:55 GMT+0100"

because they can't run in the specified timezones.